/* Generated by tools/wav2c.py — DO NOT EDIT. */
#ifndef RVSTACK_QUABRICKS_SFX_DATA_H
#define RVSTACK_QUABRICKS_SFX_DATA_H

#include <stdint.h>

#define SFX_DATA_COUNT 13

/* Mono s16 @ 48000 Hz, ordered like sound.h's SFX_* enum */
extern const int16_t * const sfx_pcm[SFX_DATA_COUNT];
extern const uint32_t sfx_bytes[SFX_DATA_COUNT];

#endif
