#!/usr/bin/env python3
"""Generate tables.h for midiplay — all the float math happens here, offline.

    tools/gen_tables.py > tables.h

Two tables:

fnum_fine[384]  OPL3 F-numbers for one octave (MIDI notes 12..23, block 0)
                in 1/32-semitone steps.  For note n in octave `oct`
                (0..7, oct 0 = notes 12..23) the same table value is used
                with block = oct, because F-num at block b encodes
                freq * 2^(20-b) / 49716 and frequency doubles per octave.

vol_atten[128]  MIDI volume (0..127) -> OPL total-level attenuation to ADD
                to the patch's carrier level (0.75 dB per step, cap 63).
                GM curve: gain_dB = 40*log10(v/127).
"""
import math

print("// tables.h — GENERATED by tools/gen_tables.py; do not edit by hand.")
print("// SPDX-License-Identifier: BSD-2-Clause")
print("#ifndef MIDIPLAY_TABLES_H")
print("#define MIDIPLAY_TABLES_H")
print("#include <stdint.h>")
print()

STEPS = 32                                   # 1/32 semitone = ~3.1 cents
vals = []
for i in range(12 * STEPS):
    note = 12.0 + i / STEPS                  # MIDI note, reference octave
    freq = 440.0 * 2.0 ** ((note - 69.0) / 12.0)
    fnum = round(freq * (1 << 20) / 49716.0)  # block 0
    assert 0 < fnum < 1024, fnum
    vals.append(fnum)

print("#define FNUM_STEPS 32                 // sub-semitone steps per semitone")
print("static const uint16_t fnum_fine[12 * FNUM_STEPS] = {")
for r in range(0, len(vals), 12):
    print("\t" + " ".join(f"{v}," for v in vals[r:r + 12]))
print("};")
print()

vol = []
for v in range(128):
    if v == 0:
        a = 63
    else:
        db = 40.0 * math.log10(127.0 / v)
        a = min(63, round(db / 0.75))
    vol.append(a)

print("static const uint8_t vol_atten[128] = {")
for r in range(0, 128, 16):
    print("\t" + " ".join(f"{v}," for v in vol[r:r + 16]))
print("};")
print()
print("#endif // MIDIPLAY_TABLES_H")
