#!/usr/bin/env python3
"""wav2c — bake data/sfx/*.wav into compat/sfx_data.{c,h} (RVSTACK port glue).

The console has no filesystem and sdl2_lite's mixer takes mono s16 @ 48 kHz
by contract (no WAV parser, no resampler at runtime — see sdk/sdl2_lite.h
MIXER). This converts upstream's 44.1 kHz WAVs once, at build time, with a
linear resample, and emits C arrays ordered EXACTLY like the SFX_* enum in
src/sound.h. Re-run after regenerating the WAVs (tools/gen_sfx.py).

Stdlib only. Usage (from sdk/quabricks):  python3 tools/wav2c.py
"""
import wave, struct, os, sys

RATE = 48000

# Must match the SFX_* enum order in src/sound.h
NAMES = [
    "move", "rotate", "softdrop", "harddrop", "lock", "lineclear",
    "tetris", "levelup", "gameover", "menu_move", "menu_select",
    "hold", "pause",
]

def load_mono_s16(path):
    with wave.open(path, "rb") as w:
        nch, width, rate, n = (w.getnchannels(), w.getsampwidth(),
                               w.getframerate(), w.getnframes())
        raw = w.readframes(n)
    assert width == 2, f"{path}: expected 16-bit PCM"
    samples = struct.unpack(f"<{n * nch}h", raw)
    if nch > 1:  # average down to mono
        samples = [sum(samples[i:i + nch]) // nch
                   for i in range(0, len(samples), nch)]
    return list(samples), rate

def resample(samples, src, dst):
    if src == dst:
        return samples
    out_n = int(len(samples) * dst / src)
    out = []
    for i in range(out_n):
        t = i * src / dst
        j = int(t)
        f = t - j
        a = samples[j]
        b = samples[j + 1] if j + 1 < len(samples) else a
        out.append(int(a + (b - a) * f))
    return out

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    outdir = os.path.join(root, "compat")
    os.makedirs(outdir, exist_ok=True)

    arrays = []
    total = 0
    for name in NAMES:
        path = os.path.join(root, "data", "sfx", name + ".wav")
        samples, rate = load_mono_s16(path)
        samples = resample(samples, rate, RATE)
        arrays.append((name, samples))
        total += len(samples)
        print(f"  {name:12s} {rate} Hz -> {len(samples)} samples")

    with open(os.path.join(outdir, "sfx_data.c"), "w") as f:
        f.write("/* Generated by tools/wav2c.py — DO NOT EDIT.\n"
                " * Mono s16 @ 48000 Hz (the sdl2_lite mixer contract),\n"
                " * resampled from the data/sfx WAVs. Order = SFX_* enum. */\n"
                "#include \"sfx_data.h\"\n\n")
        for name, samples in arrays:
            f.write(f"static const int16_t pcm_{name}[{len(samples)}] = {{\n")
            for i in range(0, len(samples), 12):
                row = ",".join(str(s) for s in samples[i:i + 12])
                f.write("\t" + row + ",\n")
            f.write("};\n\n")
        f.write("const int16_t * const sfx_pcm[SFX_DATA_COUNT] = {\n")
        for name, _ in arrays:
            f.write(f"\tpcm_{name},\n")
        f.write("};\n\nconst uint32_t sfx_bytes[SFX_DATA_COUNT] = {\n")
        for name, samples in arrays:
            f.write(f"\t{len(samples) * 2}, /* {name} */\n")
        f.write("};\n")

    with open(os.path.join(outdir, "sfx_data.h"), "w") as f:
        f.write("/* Generated by tools/wav2c.py — DO NOT EDIT. */\n"
                "#ifndef RVSTACK_QUABRICKS_SFX_DATA_H\n"
                "#define RVSTACK_QUABRICKS_SFX_DATA_H\n\n"
                "#include <stdint.h>\n\n"
                f"#define SFX_DATA_COUNT {len(NAMES)}\n\n"
                "/* Mono s16 @ 48000 Hz, ordered like sound.h's SFX_* enum */\n"
                "extern const int16_t * const sfx_pcm[SFX_DATA_COUNT];\n"
                "extern const uint32_t sfx_bytes[SFX_DATA_COUNT];\n\n"
                "#endif\n")
    print(f"Total: {total} samples ({total * 2 // 1024} KB) -> compat/sfx_data.c")

if __name__ == "__main__":
    main()
