#!/usr/bin/env python3
"""ABI guard for the RISC-V Stack console family.

LiteX assigns CSR addresses by definition order in pocket_soc.py, and every game
.bin statically compiles those offsets in (via hal.c/csr.h). So reordering or
removing a CSR silently breaks every existing binary on the next bitstream. This
tool locks the map: it snapshots the CSR name->address table and later verifies
that no LOCKED address moved. New CSRs may only be APPENDED (append is ABI-safe:
old bins never touch the new addresses; new bins gate on hwfeat feature bits).

  snapshot:  check_abi.py --snapshot <csr.h> <manifest-out>
  check:     check_abi.py --check    <csr.h> <manifest>     # exit 1 on violation

The manifest (soc/abi/abi_v1_csr_map.txt) is ABI v1 = the v0.24.0 CSR map.
"""
import re, sys

ADDR_RE = re.compile(r'#define\s+(CSR_[A-Z0-9_]+_ADDR)\s+\(CSR_BASE\s*\+\s*(0x[0-9a-fA-F]+)L?\)')

def parse(path):
    m = {}
    with open(path) as f:
        for line in f:
            g = ADDR_RE.search(line)
            if g:
                m[g.group(1)] = int(g.group(2), 16)
    return m

def snapshot(csr_h, out):
    m = parse(csr_h)
    with open(out, 'w') as f:
        f.write("# RISC-V Stack console ABI v1 — LOCKED CSR address map (v0.24.0).\n")
        f.write("# Generated by check_abi.py. Every entry's address is frozen: a\n")
        f.write("# game .bin compiles these offsets in statically, so moving one\n")
        f.write("# breaks every existing binary. New CSRs may only be APPENDED.\n")
        f.write("# name  offset(from CSR_BASE)\n")
        for name in sorted(m, key=lambda k: (m[k], k)):
            f.write(f"{name} 0x{m[name]:x}\n")
    print(f"[abi] snapshot: {len(m)} CSRs -> {out}")

def check(csr_h, manifest):
    cur = parse(csr_h)
    locked = {}
    with open(manifest) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            name, off = line.split()
            locked[name] = int(off, 16)
    moved, removed = [], []
    for name, off in locked.items():
        if name not in cur:
            removed.append(name)
        elif cur[name] != off:
            moved.append((name, off, cur[name]))
    added = sorted(set(cur) - set(locked), key=lambda k: cur[k])
    if moved or removed:
        print("[abi] *** ABI VIOLATION — locked CSRs changed ***")
        for n, o, c in moved:
            print(f"  MOVED   {n}: 0x{o:x} -> 0x{c:x}")
        for n in removed:
            print(f"  REMOVED {n} (was 0x{locked[n]:x})")
        print("Locked addresses must never move. Append new CSRs at the end instead.")
        return 1
    print(f"[abi] OK — {len(locked)} locked CSRs intact"
          + (f", {len(added)} appended ({', '.join(added)})" if added else ""))
    return 0

def main(argv):
    if len(argv) == 4 and argv[1] == '--snapshot':
        snapshot(argv[2], argv[3]); return 0
    if len(argv) == 4 and argv[1] == '--check':
        return check(argv[2], argv[3])
    print(__doc__); return 2

if __name__ == '__main__':
    sys.exit(main(sys.argv))
